/**
 * Moderation rule data: cosplayTerms.
 *
 * EDITING NOTES: these data files are the only place a word appears. Never print
 * them in a report, a .md file, a log line, or terminal output.
 *
 * Matching is whole-word, or contiguous-phrase for multi-word entries, against
 * the normalized text, so obfuscated spellings do not need listing by hand.
 */

/**
 * Words that tie a listing to cosplay.
 *
 * Deliberately generous: over-including here only makes the unrelated rule more
 * permissive, which is the safe direction to be wrong in.
 */
export const COSPLAY_TERMS: readonly string[] = [
  'wig',
  'wigs',
  'wigging',
  'costume',
  'costumes',
  'cosplay',
  'cosplayer',
  'cosplayers',
  'kigurumi',
  'prop',
  'props',
  'armor',
  'armour',
  'helmet',
  'eva foam',
  'foam',
  'fabric',
  'cloth',
  'textile',
  'sewing',
  'sew',
  'glue gun',
  'heat gun',
  'hot glue',
  'craft',
  'crafting',
  'makeup',
  'make up',
  'cosmetics',
  'contacts',
  'contact lens',
  'lenses',
  'lens',
  'photography',
  'photoshoot',
  'photo shoot',
  'session',
  'commission',
  'commissions',
  'convention',
  'con',
  'anime',
  'manga',
  'vtuber',
  'kpop',
  'series',
  'character',
  'waifu',
  'doujin',
  'dress',
  'gown',
  'kimono',
  'hakama',
  'cloak',
  'cape',
  'robe',
  'skirt',
  'jacket',
  'coat',
  'boot',
  'shoes',
  'gloves',
  'mask',
  'makeup brush',
  'printing',
  '3d print',
  '3d printed',
  'resin',
  'worbla',
  'eva',
  'paint',
  'primer',
  'airbrush',
  'brush',
  'superglue',
  'fabric glue',
  'tutorial',
  'pattern',
  'seam',
  'zipper',
  'velcro',
  'thread',
  'needle',
  'pattern making',
  'tailoring',
  'embroidery',
  'bead',
  'jewelry prop',
  'light saber',
  'lightsaber',
  'sword',
  'katana',
  'staff',
  'wand',
  'shield',
  'mecha',
  'gundam',
  'pokemon',
  'naruto',
  'one piece',
  'dragon ball',
  'final fantasy',
  'genshin',
  'honkai',
  'paimon',
  'cosplay commission',
  'photoshoot commission',
  'cosplay prop maker',
  'convention booth',
];
