/**
 * Moderation rule data: unrelated.
 *
 * EDITING NOTES: these data files are the only place a word appears. Never print
 * them in a report, a .md file, a log line, or terminal output.
 *
 * Matching is whole-word, or contiguous-phrase for multi-word entries, against
 * the normalized text, so obfuscated spellings do not need listing by hand.
 */

/**
 * Terms for goods with no cosplay connection.
 *
 * A hit on one of these is only a violation when the listing has no cosplay
 * term, no item qualifier, and no word from the selected category. A listing
 * that mixes both readings is ambiguous, and ambiguous listings are allowed.
 */
export const UNRELATED_TERMS: readonly string[] = [
  'iphone',
  'android phone',
  'smartphone',
  'cellphone',
  'mobile phone',
  'laptop',
  'notebook computer',
  'desktop computer',
  'tablet',
  'ipad',
  'monitor',
  'graphics card',
  'motherboard',
  'ram',
  'ssd',
  'hard drive',
  'usb drive',
  'router',
  'modem',
  'headphones',
  'earbuds',
  'smartwatch',
  'smart tv',
  'television',
  'camera lens',
  'printer',
  'scanner',
  'car',
  'cars',
  'motorcycle',
  'motorbike',
  'bicycle',
  'jeepney',
  'tricycle',
  'truck',
  'van',
  'bus',
  'tractor',
  'trailer',
  'engine',
  'chassis',
  'windshield',
  'tires',
  'rims',
  'motor',
  'headlight',
  'taillight',
  'house for rent',
  'apartment for rent',
  'lot for sale',
  'land for sale',
  'real estate',
  'condominium',
  'subdivision',
  'floor plan',
  'lot area',
  'lease',
  'tenancy',
  'rent a house',
  'rent an apartment',
  'job vacancy',
  'job opening',
  'hiring',
  'resume',
  'cv template',
  'part time job',
  'full time job',
  'work from home',
  'business opportunity',
  'mlm',
  'recruitment',
  'vacancy',
  'puppy for sale',
  'kitten for sale',
  'dog for sale',
  'cat for sale',
  'poultry',
  'chicken live',
  'goat for sale',
  'piglet',
  'cattle',
  'livestock',
  'fish tank',
  'aquarium fish',
  'bird cage',
  'refrigerator',
  'washing machine',
  'air conditioner',
  'microwave oven',
  'television set',
  'sofa',
  'bed frame',
  'wardrobe cabinet',
  'dining table',
  'office chair',
  'water heater',
  'gas stove',
  'car battery',
  'used oil',
  'tire',
  'tyre',
  'rim',
  'gearbox',
];
